name: snacked
services:
  assets:
    build:
      context: /Users/dious/Code/github.com/ndious/snacked/docker/assets
      dockerfile: Dockerfile
      target: dev
    networks:
      default: null
    volumes:
      - type: bind
        source: /Users/dious/Code/github.com/ndious/snacked/assets/static.ts
        target: /usr/src/app/static.ts
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /Users/dious/Code/github.com/ndious/snacked/assets/css
        target: /usr/src/app/css
        read_only: true
        bind:
          create_host_path: true
      - type: volume
        source: generated-data
        target: /usr/src/app/generated
        volume: {}
      - type: bind
        source: /Users/dious/Code/github.com/ndious/snacked/internal
        target: /usr/src/app/src
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /Users/dious/Code/github.com/ndious/snacked/docker/assets/package.json
        target: /usr/src/app/package.json
        bind:
          create_host_path: true
      - type: bind
        source: /Users/dious/Code/github.com/ndious/snacked/docker/assets/node_modules
        target: /usr/src/app/node_modules
        bind:
          create_host_path: true
      - type: bind
        source: /Users/dious/Code/github.com/ndious/snacked/var/log/assets
        target: /usr/src/app/log
        bind:
          create_host_path: true
  db:
    environment:
      POSTGRES_DB: snacked
      POSTGRES_PASSWORD: Sn4ck3d
      POSTGRES_USER: Sn4ck3d
    image: postgres:alpine
    networks:
      default: null
    ports:
      - mode: ingress
        target: 5432
        published: "5432"
        protocol: tcp
  snacked:
    build:
      context: /Users/dious/Code/github.com/ndious/snacked/docker/go
      dockerfile: Dockerfile
      target: dev
    networks:
      default: null
    ports:
      - mode: ingress
        target: 1337
        published: "1337"
        protocol: tcp
      - mode: ingress
        target: 2345
        published: "2345"
        protocol: tcp
    volumes:
      - type: bind
        source: /Users/dious/Code/github.com/ndious/snacked/internal
        target: /usr/src/app/internal
        bind:
          create_host_path: true
      - type: bind
        source: /Users/dious/Code/github.com/ndious/snacked/config
        target: /usr/src/app/config
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /Users/dious/Code/github.com/ndious/snacked/go.mod
        target: /usr/src/app/go.mod
        bind:
          create_host_path: true
      - type: bind
        source: /Users/dious/Code/github.com/ndious/snacked/go.sum
        target: /usr/src/app/go.sum
        bind:
          create_host_path: true
      - type: bind
        source: /Users/dious/Code/github.com/ndious/snacked/docker/go/vendor
        target: /usr/src/app/vendor
        bind:
          create_host_path: true
      - type: volume
        source: air-data
        target: /usr/src/app/.tmp
        volume: {}
      - type: bind
        source: /Users/dious/Code/github.com/ndious/snacked/docker/go/.air.toml
        target: /usr/src/app/.air.toml
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /Users/dious/Code/github.com/ndious/snacked/var/log/snacked
        target: /usr/src/app/log
        bind:
          create_host_path: true
  tests:
    build:
      context: /Users/dious/Code/github.com/ndious/snacked/docker/go
      dockerfile: Dockerfile
      target: test-watch
    networks:
      default: null
    volumes:
      - type: bind
        source: /Users/dious/Code/github.com/ndious/snacked/internal
        target: /usr/src/app/internal
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /Users/dious/Code/github.com/ndious/snacked/config
        target: /usr/src/app/config
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /Users/dious/Code/github.com/ndious/snacked/go.mod
        target: /usr/src/app/go.mod
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /Users/dious/Code/github.com/ndious/snacked/go.sum
        target: /usr/src/app/go.sum
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /Users/dious/Code/github.com/ndious/snacked/docker/go/vendor
        target: /usr/src/app/vendor
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /Users/dious/Code/github.com/ndious/snacked/var/log/tests
        target: /usr/src/app/log
        bind:
          create_host_path: true
  traefik:
    image: traefik:v2.10
    labels:
      traefik.http.routers.traefik-dashboard: "true"
    networks:
      default: null
    ports:
      - mode: host
        target: 80
        published: "80"
        protocol: tcp
      - mode: host
        target: 443
        published: "443"
        protocol: tcp
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /Users/dious/Code/github.com/ndious/snacked/docker/traefik/traefik/traefik.toml
        target: /etc/traefik/traefik.toml
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /Users/dious/Code/github.com/ndious/snacked/docker/traefik/traefik/traefik.d
        target: /etc/traefik/traefik.d
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /Users/dious/Code/github.com/ndious/snacked/var/log/traefik
        target: /logs
        bind:
          create_host_path: true
      - type: bind
        source: /Users/dious/Code/github.com/ndious/snacked/var/certs
        target: /etc/certs
        read_only: true
        bind:
          create_host_path: true
networks:
  default:
    name: snacked_default
volumes:
  air-data:
    name: snacked_air-data
  generated-data:
    name: snacked_generated-data
