version: "3.8"

services:
  assets:
    build:
      context: "${ASSETS_DIR}"
      dockerfile: Dockerfile
      target: dev
    volumes:
      - "${ASSETS_DIR}/srv:${APP_DIR}/srv:rw,delegated"
      - "${ASSETS_DIR}/entrypoint.sh:${APP_DIR}/entrypoint.sh"
      - "${ASSETS_DIR}/package.json:${APP_DIR}/package.json"
