version: "3.8"

services:
  assets:
    build:
      context: "${ASSETS_DIR}"
      dockerfile: Dockerfile
      target: dev
    volumes:
      - "${ASSETS_DIR}/static.ts:${APP_DIR}/static.ts:ro"
      - "${ASSETS_DIR}/package.json:${APP_DIR}/package.json:rw,delegated"
      - "${ASSETS_DIR}/node_modules:${APP_DIR}/node_modules:rw,delegated"
