version: "3.8"

name: snacked

volumes:
  air-data:

include:
  - "${ASSETS_DIR}/compose.yml"

services:
  traefik:
    image: traefik:v2.10
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${TRAEFIK_DIR}/traefik/traefik.toml:/etc/traefik/traefik.toml:ro"
      - "${TRAEFIK_DIR}/traefik/traefik.d:/etc/traefik/traefik.d:ro"
      - "${VAR_DIR}/log/traefik:/logs"
      - "${VAR_DIR}/certs:/etc/certs:ro"
    labels:
      - "traefik.http.routers.traefik-dashboard=true"

  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB}"
    ports:
      - 5432:5432

  snacked:
    build:
      context: "${GO_DIR}"
      dockerfile: Dockerfile
      target: dev
    volumes:
      - "${ROOT_DIR}/internal:${APP_DIR}/internal:rw,delegated"
      - "${ROOT_DIR}/config:${APP_DIR}/config:ro"
      - "${ROOT_DIR}/go.mod:${APP_DIR}/go.mod:rw,delegated"
      - "${ROOT_DIR}/go.sum:${APP_DIR}/go.sum:rw,delegated"
      - "${GO_DIR}/vendor:${APP_DIR}/vendor:rw,delegated"
      - "air-data:${APP_DIR}/.tmp:rw,delegated"
      - "${GO_DIR}/.air.toml:${APP_DIR}/.air.toml:ro"
      - "${VAR_DIR}/log/snacked:${APP_DIR}/log:rw,delegated"
    ports:
      - 1337:1337
      - 2345:2345

  tests:
    build:
      context: "${GO_DIR}"
      dockerfile: Dockerfile
      target: test-watch
    volumes:
      - "${ROOT_DIR}/internal:${APP_DIR}/internal:ro"
      - "${ROOT_DIR}/config:${APP_DIR}/config:ro"
      - "${ROOT_DIR}/go.mod:${APP_DIR}/go.mod:ro"
      - "${ROOT_DIR}/go.sum:${APP_DIR}/go.sum:ro"
      - "${GO_DIR}/vendor:${APP_DIR}/vendor:ro"
      - "${VAR_DIR}/log/tests:${APP_DIR}/log:rw,delegated"
